* Library Information
- Filename: bbdb-ext.el
- Description: Extra commands for BBDB
- Author: Joe Bloggs <vapniks@yahoo.com>
- Maintainer: Joe Bloggs <vapniks@yahoo.com>
- Copyleft (Ↄ) 2013, Joe Bloggs, all rites reversed.
- Created: 2010
- Version: 0.1
- Last-Updated: 2013-05-13 19:19:43 By: Joe Bloggs
- URL: https://github.com/vapniks/bbdb-ext
- Keywords: extensions
- Compatibility: GNU Emacs 24.3.1
- Package-Requires: ((bbdb "2.36"))

* Commentary
Bitcoin donations gratefully accepted: 1GWis4cd4aokQrWxAd3ZASrsye5CGq5LJY

This file contains some extra commands for BBDB. 

* Keybindings
Here is a list of the keybindings:

- "g"    : Search address of current record on google maps
- "S d"  : Show records with address field matching regexp (use "^$" to show records with no address)
- "/ S"  : Show records that match regexp in either name, company, network, address or notes fields
- "/ n"  : Show records with name field matching regexp
- "/ c"  : Show records with company field matching regexp
- "/ a"  : Show records with network address field matching regexp
- "/ o"  : Show records with notes field matching regexp
- "/ p"  : Show records with phones field matching regexp
- "/ d"  : Show records with address field matching regexp (use "^$" to show records with no address)
- "/ /"  : Show all records

* Commands
Below are complete command list:

- `bbdb-google-map'
  Search REC's address field using Google Maps.
- `bbdb-recursive-search'
  Display all entries in the *BBDB* buffer matching the REGEX in either the name(s), company, network address, or notes.
- `bbdb-recursive-search-name'
  Display all entries in the *BBDB* buffer matching the REGEX in the name (or ``alternate'' names) field.
- `bbdb-recursive-search-company'
  Display all entries in *BBDB* buffer matching REGEX in the company field.
- `bbdb-recursive-search-net'
  Display all entries in *BBDB* buffer matching regexp REGEX in the network address.
- `bbdb-recursive-search-notes'
  Display all entries in *BBDB* buffer matching REGEX in the named notes field.
- `bbdb-recursive-search-phones'
  Display all entries in *BBDB* buffer matching the REGEX in the phones field.
- `bbdb-recursive-search-address'
  Display all entries in the *BBDB* buffer matching the REGEX in the address fields.
- `bbdb-disable-all-limits'
  Display all entries in BBDB database.
- `bbdb-address'
  Display all entries in the BBDB matching the REGEX in the address field.

* Installation

 - If you have [[http://www.marmalade-repo.org/][marmalade-repo.org]], this bbdb-ext is part of the emacs packages you can install.  Just type M-x package-install bbdb-ext marmalade 
 - Otherwise download the library from here Lisp:bbdb-ext, and put it in a directory in the emacs load path, like ~/.emacs.d
 - Add (require 'bbdb-ext) in your ~/.emacs file
