* Commentary
Bitcoin donations gratefully accepted: 1GWis4cd4aokQrWxAd3ZASrsye5CGq5LJY

This file contains some extra commands for BBDB. 


* Commands

Below is a complete list of commands:

 - `bbdb-recursive-search'
   Perform recursive search on FIELD.
   Keybinding: / ?
 - `bbdb-google-map'
   Search REC's address field using Google Maps.
   Keybinding: G
 - `bbdb-recursive-search-all'
   Display all entries in the *BBDB* buffer matching the REGEX in either the name(s), company, network address, or notes.
   Keybinding: / S
 - `bbdb-recursive-search-name'
   Display all entries in the *BBDB* buffer matching the REGEX in the name (or ``alternate'' names) field.
   Keybinding: / n
 - `bbdb-recursive-search-company'
   Display all entries in *BBDB* buffer matching REGEX in the company field.
   Keybinding: / c
 - `bbdb-recursive-search-net'
   Display all entries in *BBDB* buffer matching regexp REGEX in the network/email address.
   Keybinding: / e
 - `bbdb-recursive-search-xfields'
   Display all BBDB records for which xfield FIELD matches REGEXP.
   Keybinding: / x
 - `bbdb-recursive-search-phones'
   Display all entries in *BBDB* buffer matching the REGEX in the phones field.
   Keybinding: / p
 - `bbdb-recursive-search-address'
   Display all entries in the *BBDB* buffer matching the REGEX in the address fields.
   Keybinding: / d
 - `bbdb-disable-all-limits'
   Display all entries in BBDB database.
   Keybinding: g

* Installation
Put bbdb-ext.el in a directory in your load-path, e.g. ~/.emacs.d/
You can add a directory to your load-path with the following line in ~/.emacs
(add-to-list 'load-path (expand-file-name "~/elisp"))
where ~/elisp is the directory you want to add 
(you don't need to do this for ~/.emacs.d - it's added by default).

Add the following to your ~/.emacs startup file.

(require 'bbdb-ext)
